In [113]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from collections import Counter


text = "Composed of 3 CDs and quite a few songs (I haven't an exact count), \          all of which are heart-rendering and impressively remarkable . \          It has everything for every listener -- from fast-paced and energetic \          (Dancing the Tokage or Termina Home), to slower and more haunting (Dragon God), \          to purely beautifully composed (Time's Scar), \          to even some fantastic vocals (Radical Dreamers).\          This is one of the best videogame soundtracks out there, \          and surely Mitsuda's best ever. ^_^"
for char in '.,\n "" \\ ( ) .^_^ 3':
    text=text.replace(char,' ')
text = text.lower()
# split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
word_list = text.split()
print(word_list)


['composed', 'of', 'cds', 'and', 'quite', 'a', 'few', 'songs', 'i', "haven't", 'an', 'exact', 'count', 'all', 'of', 'which', 'are', 'heart-rendering', 'and', 'impressively', 'remarkable', 'it', 'has', 'everything', 'for', 'every', 'listener', '--', 'from', 'fast-paced', 'and', 'energetic', 'dancing', 'the', 'tokage', 'or', 'termina', 'home', 'to', 'slower', 'and', 'more', 'haunting', 'dragon', 'god', 'to', 'purely', 'beautifully', 'composed', "time's", 'scar', 'to', 'even', 'some', 'fantastic', 'vocals', 'radical', 'dreamers', 'this', 'is', 'one', 'of', 'the', 'best', 'videogame', 'soundtracks', 'out', 'there', 'and', 'surely', "mitsuda's", 'best', 'ever']


In [68]:
token_list= ( [w for w in word_list if len(w)>1] )
print(token_list)

['composed', 'of', 'cds', 'and', 'quite', 'few', 'songs', "haven't", 'an', 'exact', 'count', 'all', 'of', 'which', 'are', 'heart-rendering', 'and', 'impressively', 'remarkable', 'it', 'has', 'everything', 'for', 'every', 'listener', '--', 'from', 'fast-paced', 'and', 'energetic', 'dancing', 'the', 'tokage', 'or', 'termina', 'home', 'to', 'slower', 'and', 'more', 'haunting', 'dragon', 'god', 'to', 'purely', 'beautifully', 'composed', "time's", 'scar', 'to', 'even', 'some', 'fantastic', 'vocals', 'radical', 'dreamers', 'this', 'is', 'one', 'of', 'the', 'best', 'videogame', 'soundtracks', 'out', 'there', 'and', 'surely', "mitsuda's", 'best', 'ever.']


In [69]:
if '--' in token_list: token_list.remove('--')
print(token_list)

['composed', 'of', 'cds', 'and', 'quite', 'few', 'songs', "haven't", 'an', 'exact', 'count', 'all', 'of', 'which', 'are', 'heart-rendering', 'and', 'impressively', 'remarkable', 'it', 'has', 'everything', 'for', 'every', 'listener', 'from', 'fast-paced', 'and', 'energetic', 'dancing', 'the', 'tokage', 'or', 'termina', 'home', 'to', 'slower', 'and', 'more', 'haunting', 'dragon', 'god', 'to', 'purely', 'beautifully', 'composed', "time's", 'scar', 'to', 'even', 'some', 'fantastic', 'vocals', 'radical', 'dreamers', 'this', 'is', 'one', 'of', 'the', 'best', 'videogame', 'soundtracks', 'out', 'there', 'and', 'surely', "mitsuda's", 'best', 'ever.']


In [116]:
# filter out stop words

stop_words = set(stopwords.words('English'))
tokens = [w for w in token_list if not w in stop_words]
print(tokens)


['composed', 'cds', 'quite', 'songs', 'exact', 'count', 'heart-rendering', 'impressively', 'remarkable', 'everything', 'every', 'listener', 'fast-paced', 'energetic', 'dancing', 'tokage', 'termina', 'home', 'slower', 'haunting', 'dragon', 'god', 'purely', 'beautifully', 'composed', "time's", 'scar', 'even', 'fantastic', 'vocals', 'radical', 'dreamers', 'one', 'best', 'videogame', 'soundtracks', 'surely', "mitsuda's", 'best', 'ever.']


In [131]:
from collections import Counter
with open("positive-words.txt",'r') as f:
    positive_words=[line.strip() for line in f]

#positive_words
#print(positive_words)

positive_tokens=[token for token in tokens \
                 if token in positive_words]

print(len(positive_tokens))
Counter_positive_tokens = Counter(positive_tokens)
print(Counter_positive_tokens)

8
Counter({'best': 2, 'impressively': 1, 'remarkable': 1, 'fast-paced': 1, 'energetic': 1, 'beautifully': 1, 'fantastic': 1})


In [118]:
from collections import Counter
with open("negative-words.txt",'r') as f:
    negative_words=[line.strip() for line in f]

#positive_words
#print(negative_words)

negative_tokens=[token for token in tokens \
                 if token in negative_words]

print(negative_tokens)
Counter_negative_tokens = Counter(negative_tokens)
print(Counter_negative_tokens)

['slower', 'haunting', 'scar', 'radical']
Counter({'slower': 1, 'haunting': 1, 'scar': 1, 'radical': 1})


In [135]:
# Exercise 3.5.2.2 # check if a positive word not preceded by negation words
# e.g. not, too, n't, no, cannot

import nltk
nltk.download()

# this is not an exhaustive list of negation words!
negations=[ "'not', 'no', 'isn't', 'wasn't', 'aren't', 'weren't', 'don't', 'didn't', 'cannot', 'couldn't', 'won't', 'neither', 'nor', 'won't', 'neither', 'nor'"]
tokens1 = nltk.word_tokenize(text)  

#print(tokens)

positive_tokens=[]
for idx, token in enumerate(tokens1):
    if token in positive_words:
        if idx>0:
            if tokens1[idx-1] not in negations:
                positive_tokens.append(token)
        else:
            positive_tokens.append(token)


print((positive_tokens))


showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
['impressively', 'remarkable', 'fast-paced', 'energetic', 'beautifully', 'fantastic', 'best', 'best']


In [129]:
# positive word preceded by a negation word 
import nltk
nltk.download()

# this is not an exhaustive list of negation words!
negations=[ "'not', 'no', 'haven't', 'wasn't', 'aren't', 'weren't', 'don't', 'didn't', 'cannot', 'couldn't', 'won't', 'neither', 'nor', 'won't', 'neither', 'nor'"]
tokens1 = nltk.word_tokenize(text)  

#print(tokens)

negative_tokens=[]
for idx, token in enumerate(tokens1):
    if token in positive_words:
        if idx>0:
            if tokens1[idx-1] in negations:
                negative_tokens.append(token)
        else:
            negative_tokens.append(token)


print(negative_tokens)

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
[]


In [136]:
# Exercise 3.5.2.2 # a negative word not preceded by a negation word 
# e.g. not, too, n't, no, cannot

import nltk
nltk.download()

# this is not an exhaustive list of negation words!
negations=[ "'not', 'no', 'isn't', 'wasn't', 'aren't', 'weren't', 'don't', 'didn't', 'cannot', 'couldn't', 'won't', 'neither', 'nor', 'won't', 'neither', 'nor'"]
tokens1 = nltk.word_tokenize(text)  

#print(tokens)

negative_tokens=[]
for idx, token in enumerate(tokens1):
    if token in negative_words:
        if idx>0:
            if tokens1[idx-1] not in negations:
                negative_tokens.append(token)
        else:
            negative_tokens.append(token)


print((negative_tokens))

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
['slower', 'haunting']


In [137]:
# negative word preceded by a negation word 
import nltk
nltk.download()

# this is not an exhaustive list of negation words!
negations=[ "'not', 'no', 'haven't', 'wasn't', 'aren't', 'weren't', 'don't', 'didn't', 'cannot', 'couldn't', 'won't', 'neither', 'nor', 'won't', 'neither', 'nor'"]
tokens1 = nltk.word_tokenize(text)  

#print(tokens)

positive_tokens=[]
for idx, token in enumerate(tokens1):
    if token in negative_words:
        if idx>0:
            if tokens1[idx-1] in negations:
                positive_tokens.append(token)
        else:
            positive_tokens.append(token)


print(positive_tokens)

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
[]


In [81]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import wordnet
from scipy.spatial import distance
import numpy as np
from matplotlib import pyplot as plt

In [103]:
def tokenize(text):        
                 
    # tokenize into words   
    for char in '. ,\n "" \\ ( ) ^_^ 3':
        text=text.replace(char,' ')
        
    # lower capitalization
    text = text.lower()
    
    # split returns a list of words delimited by sequences of whitespace (including tabs, newlines, etc, like re's \s) 
    word_list = text.split()
    #print(word_list)
    
    # remove words less than two letters
    token_list= ( [w for w in word_list if len(w)>1] )
    #print(token_list)
    
    # remove underscore as tokens    
    if '--' in token_list: token_list.remove('--')
    #print(token_list)
    
    
    # remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in token_list if not w in stop_words]
    token_count=nltk.FreqDist(tokens)

    return token_count

In [104]:
docs1=pd.read_csv("amazon_review_300.csv", header=0)
docs1.head()
docs=data["review"]
print(docs)

0      This sound track was beautiful! It paints the ...
1      I'm reading a lot of reviews saying that this ...
2      This soundtrack is my favorite music of all ti...
3      I truly like this soundtrack and I enjoy video...
4      If you've played the game, you know how divine...
5      I am quite sure any of you actually taking the...
6      This is a self-published book, and if you want...
7      I loved Whisper of the wicked saints. The stor...
8      I just finished reading Whisper of the Wicked ...
9      This was a easy to read book that made me want...
10     A complete waste of time. Typographical errors...
11     This was a great book,I just could not put it ...
12     I thought this book was brilliant, but yet rea...
13     I guess you have to be a romance novel lover f...
14     I feel I have to write to keep others from was...
15     It's glaringly obvious that all of the glowing...
16     When you hear folks say that they don't make '...
17     After I had a DVT my doc

In [105]:
docs_tokens={idx:tokenize(doc) \
             for idx,doc in enumerate(docs)}

print(docs_tokens)

{0: FreqDist({'would': 2, 'game': 2, 'music!': 2, 'played': 2, 'sound': 1, 'track': 1, 'beautiful!': 1, 'paints': 1, 'senery': 1, 'mind': 1, ...}), 1: FreqDist({"i'm": 2, 'reading': 1, 'lot': 1, 'reviews': 1, 'saying': 1, 'best': 1, "'game": 1, "soundtrack'": 1, 'figured': 1, "i'd": 1, ...}), 2: FreqDist({'soundtrack': 3, 'music': 2, 'time': 2, 'played': 2, 'game': 2, 'chrono': 2, 'favorite': 1, 'hands': 1, 'intense': 1, 'sadness': 1, ...}), 3: FreqDist({'game': 3, 'music': 3, 'truly': 2, 'like': 2, 'soundtrack': 2, 'enjoy': 2, 'video': 2, 'disk': 2, 'god': 2, 'played': 1, ...}), 4: FreqDist({'game': 2, 'music': 2, 'dreamers:': 2, 'played': 1, 'know': 1, 'divine': 1, 'is!': 1, 'every': 1, 'single': 1, 'song': 1, ...}), 5: FreqDist({'quite': 2, 'game': 2, 'least': 2, "mitsuda's": 2, 'every': 2, 'composed': 2, 'one': 2, 'best': 2, 'sure': 1, 'actually': 1, ...}), 6: FreqDist({'book': 5, 'ms': 2, "can't": 2, 'reading': 2, 'kind': 2, 'far': 2, 'self-published': 1, 'want': 1, 'know': 1, 'wh

In [75]:
# step 3. get document-term matrix
dtm=pd.DataFrame.from_dict(docs_tokens, orient="index" )
dtm=dtm.fillna(0)
dtm


sound  track  beautiful!  paints  senery  mind  well  would  recomend  \
0      1.0    1.0         1.0     1.0     1.0   1.0   1.0    2.0       1.0   
1      0.0    0.0         0.0     0.0     0.0   0.0   0.0    1.0       0.0   
2      0.0    0.0         0.0     0.0     0.0   0.0   1.0    1.0       0.0   
3      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
4      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
5      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
6      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
7      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
8      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
9      0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
10     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
11     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
12     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
13     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
14     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
15     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
16     1.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
17     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
18     0.0    0.0         0.0     0.0     0.0   0.0   0.0    1.0       0.0   
19     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
20     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
21     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
22     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
23     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
24     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
25     0.0    0.0         0.0     0.0     0.0   0.0   0.0    2.0       0.0   
26     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
27     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
28     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
29     0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
..     ...    ...         ...     ...     ...   ...   ...    ...       ...   
270    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
271    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
272    0.0    0.0         0.0     0.0     0.0   0.0   0.0    1.0       0.0   
273    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
274    0.0    0.0         0.0     0.0     0.0   0.0   1.0    0.0       0.0   
275    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
276    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
277    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
278    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
279    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
280    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
281    0.0    0.0         0.0     0.0     0.0   1.0   0.0    0.0       0.0   
282    0.0    0.0         0.0     0.0     0.0   0.0   1.0    0.0       0.0   
283    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
284    0.0    0.0         0.0     0.0     0.0   0.0   1.0    0.0       0.0   
285    0.0    0.0         0.0     0.0     0.0   0.0   1.0    1.0       0.0   
286    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
287    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
288    0.0    0.0         0.0     0.0     0.0   0.0   0.0    0.0       0.0   
289    0.0    0.0         0

In [76]:
tf=dtm.values
doc_len=tf.sum(axis=1)
tf=np.divide(tf.T, doc_len).T
print(tf)


[[0.025      0.025      0.025      ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.03333333 0.03333333 0.        ]
 [0.         0.         0.         ... 0.         0.         0.05      ]]


In [77]:
# step 5. get idf
df=np.where(tf>0,1,0)
    #idf=np.log(np.divide(len(docs), \
    #    np.sum(df, axis=0)))+1
print(df)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]]


In [106]:
def tfidf(docs):
    # step 2. process all documents to get list of token list
    docs_tokens={idx:tokenize(doc) \
             for idx,doc in enumerate(docs)}

    # step 3. get document-term matrix
    dtm=pd.DataFrame.from_dict(docs_tokens, orient="index" )
    dtm=dtm.fillna(0)
    
    # step 4. get normalized term frequency (tf) matrix        
    tf=dtm.values
    doc_len=tf.sum(axis=1)
    print(doc_len)
    tf=np.divide(tf.T, doc_len).T
    
    # step 5. get idf
    df=np.where(tf>0,1,0)
    #idf=np.log(np.divide(len(docs), \
    #    np.sum(df, axis=0)))+1

    smoothed_idf=np.log(np.divide(len(docs)+1, np.sum(df, axis=0)+1))+1    
    smoothed_tf_idf=tf*smoothed_idf
    
    return smoothed_tf_idf

In [107]:
def find_similar_doc(docs, doc_id):
    tf_idf=tfidf(docs)
    top_sim_score=1-distance.squareform(distance.pdist(tf_idf, 'cosine'))
    
    # the best score is always at the diagnal. a doc is similar to itself with score =1
    # return the second largest
    top_sim_index=np.argsort(top_sim_score[doc_id])[::-1][1]
    
    return  top_sim_index, top_sim_score[doc_id,top_sim_index]

In [109]:
if __name__ == "__main__":  
    
      
    data=pd.read_csv("amazon_review_300.csv", header=0)
    data.head()


    # Test Q2
    print("\nTest Q2")
    doc_id=207
    sim_doc_id, sim = find_similar_doc(data["review"], doc_id) 
    print("\nSimilarity between {0} and {1} is {2:.2f}: ".format(doc_id, sim_doc_id, sim))    
    print("\nselected doc: ", data.loc[doc_id]["review"])    
    print("\nsimilar doc: ", data.loc[sim_doc_id]["review"]) 

    doc_id=10
    sim_doc_id, sim = find_similar_doc(data["review"], doc_id) 
    print("\nSimilarity between {0} and {1} is {2:.2f}: ".format(doc_id, sim_doc_id, sim))    
    print("\nselected doc: ", data.loc[doc_id]["review"])    
    print("\nsimilar doc: ", data.loc[sim_doc_id]["review"])


Test Q2
[40. 45. 68. 73. 42. 68. 74. 39. 42. 26. 20. 42. 26. 44. 58. 19. 64. 64.
 31. 17. 39. 74. 87. 66. 22. 56. 46. 24. 54. 72. 45. 73. 26. 86. 13. 66.
 58. 41. 12. 31. 25. 84. 16. 22. 10. 35. 54. 48. 17. 40. 20. 75. 44. 45.
 22. 29. 42. 26.  9. 14. 37. 27. 52. 43. 32. 64. 35. 31. 32. 32. 27. 91.
 18. 63. 42. 57. 55. 13. 12. 11. 54. 90. 27. 17. 10. 36. 16. 12. 56. 20.
 46. 80. 33. 35. 14. 23. 16. 16. 16.  9. 10. 72. 36. 87. 15. 13. 59. 44.
 22. 16. 89. 23. 17. 15.  9. 37. 25. 74. 58. 48. 46. 25. 15. 37. 48. 32.
 33. 13. 13. 19. 18. 29. 36. 21. 63. 11. 59. 34. 27. 88. 38. 23. 35.  8.
 52. 29. 84. 31. 38. 19. 35. 47. 44. 28. 30. 29. 70. 58. 71. 22. 43. 84.
 73. 15. 24. 82. 17. 10. 47. 10. 24. 22. 11. 87. 17. 13.  7. 35. 47. 20.
 48. 18. 39. 51. 49. 61. 12. 21. 31. 97. 84. 82. 25. 34. 16. 25. 42. 31.
 23. 15. 63. 40. 37. 58.  7. 16. 15. 25. 41. 31. 31. 41. 55. 82. 43. 32.
 36. 27. 55. 41. 55. 53. 18. 21. 34. 43. 24. 17. 24. 93. 15. 37. 29. 34.
 55. 46. 27. 42. 24. 59. 20. 44. 37.  7. 6

In [120]:
def find_similar_doc(docs, doc_id):
    
    
    docs_tokens={idx:tokenize(doc) \
             for idx,doc in enumerate(docs)}

    # step 3. get document-term matrix
    dtm=pd.DataFrame.from_dict(docs_tokens, orient="index" )
    dtm=dtm.fillna(0)
    
    # step 4. get normalized term frequency (tf) matrix        
    tf=dtm.values
    doc_len=tf.sum(axis=1)
    print(doc_len)
    tf=np.divide(tf.T, doc_len).T
    
    # step 5. get idf
    df=np.where(tf>0,1,0)
    #idf=np.log(np.divide(len(docs), \
    #    np.sum(df, axis=0)))+1

    smoothed_idf=np.log(np.divide(len(docs)+1, np.sum(df, axis=0)+1))+1    
    smoothed_tf_idf=tf*smoothed_idf
    
   
    top_sim_score=1-distance.squareform(distance.pdist(smoothed_tf_idf, 'cosine'))
    
    # the best score is always at the diagnal. a doc is similar to itself with score =1
    # return the second largest
    top_sim_index=np.argsort(top_sim_score[doc_id])[::-1][1]
    
    return  top_sim_index, top_sim_score[doc_id,top_sim_index]

In [121]:
if __name__ == "__main__":  
    
      
    data=pd.read_csv("amazon_review_300.csv", header=0)
    data.head()


    # Test Q2
    print("\nTest Q2")
    doc_id=207
    sim_doc_id, sim = find_similar_doc(data["review"], doc_id) 
    print("\nSimilarity between {0} and {1} is {2:.2f}: ".format(doc_id, sim_doc_id, sim))    
    print("\nselected doc: ", data.loc[doc_id]["review"])    
    print("\nsimilar doc: ", data.loc[sim_doc_id]["review"]) 

    doc_id=10
    sim_doc_id, sim = find_similar_doc(data["review"], doc_id) 
    print("\nSimilarity between {0} and {1} is {2:.2f}: ".format(doc_id, sim_doc_id, sim))    
    print("\nselected doc: ", data.loc[doc_id]["review"])    
    print("\nsimilar doc: ", data.loc[sim_doc_id]["review"])


Test Q2
[40. 45. 68. 73. 42. 68. 74. 39. 42. 26. 20. 42. 26. 44. 58. 19. 64. 64.
 31. 17. 39. 74. 87. 66. 22. 56. 46. 24. 54. 72. 45. 73. 26. 86. 13. 66.
 58. 41. 12. 31. 25. 84. 16. 22. 10. 35. 54. 48. 17. 40. 20. 75. 44. 45.
 22. 29. 42. 26.  9. 14. 37. 27. 52. 43. 32. 64. 35. 31. 32. 32. 27. 91.
 18. 63. 42. 57. 55. 13. 12. 11. 54. 90. 27. 17. 10. 36. 16. 12. 56. 20.
 46. 80. 33. 35. 14. 23. 16. 16. 16.  9. 10. 72. 36. 87. 15. 13. 59. 44.
 22. 16. 89. 23. 17. 15.  9. 37. 25. 74. 58. 48. 46. 25. 15. 37. 48. 32.
 33. 13. 13. 19. 18. 29. 36. 21. 63. 11. 59. 34. 27. 88. 38. 23. 35.  8.
 52. 29. 84. 31. 38. 19. 35. 47. 44. 28. 30. 29. 70. 58. 71. 22. 43. 84.
 73. 15. 24. 82. 17. 10. 47. 10. 24. 22. 11. 87. 17. 13.  7. 35. 47. 20.
 48. 18. 39. 51. 49. 61. 12. 21. 31. 97. 84. 82. 25. 34. 16. 25. 42. 31.
 23. 15. 63. 40. 37. 58.  7. 16. 15. 25. 41. 31. 31. 41. 55. 82. 43. 32.
 36. 27. 55. 41. 55. 53. 18. 21. 34. 43. 24. 17. 24. 93. 15. 37. 29. 34.
 55. 46. 27. 42. 24. 59. 20. 44. 37.  7. 6